### PR TITLE
weevely: upgrade to python3

### PR DESCRIPTION
**Pull request by noraj**

### CODE REVIEW

**Comment by Edu4rdSHL** [comment]
The package versión is still the same?

**Comment by noptrix** [comment]
wow nice thanks for this @noraj. yeah @Edu4rdSHL i will bump

**Comment by noptrix** [comment]
@Edu4rdSHL btw no, the versio is correct but we missed to switch to py3 and the current version in BA repo still uses py2 simply. so it's correct here just to pkgrel. thanks guys

**Comment by Edu4rdSHL** [comment]
No problem, I was just thinking why the package was bumped from python2 to python3 without a pkgver bump.

> but we missed to switch to py3 and the current version in BA repo still uses py2 simply.

I suspected that was happening. Thanks for clarifying.

**Pull request merged**
