### PR TITLE
[WIP] add jbytemod

### PR DESCRIPTION
**Pull request by noraj**
- [ ] Need to wait for this upstream issue: https://github.com/GraxCode/JByteMod-Beta/issues/86

related to #2812

### CODE REVIEW

**Comment by noptrix** [comment]
@noraj any news on this?

**Comment by ikstream** [comment]
Just looked into the tool and there is an open PR that addresses the issue. Seems like an abandoned tool. We could apply the PR as a patch to fix the tool in our repo

**Comment by noraj** [comment]
> @noraj any news on this?

Nop, abandoned since 2019.

> Just looked into the tool and there is an open PR that addresses the issue. Seems like an abandoned tool. We could apply the PR as a patch to fix the tool in our repo

Yes if we don't have to maintain it after that.

**Comment by ikstream** [comment]
> > Just looked into the tool and there is an open PR that addresses the issue. Seems like an abandoned tool. We could apply the PR as a patch to fix the tool in our repo
> 
> Yes if we don't have to maintain it after that.

As it is abandoned since 2019 I don't expect any maintenance overhead with a possible patch

**Comment by noraj** [comment]
> > > Just looked into the tool and there is an open PR that addresses the issue. Seems like an abandoned tool. We could apply the PR as a patch to fix the tool in our repo
> > 
> > 
> > Yes if we don't have to maintain it after that.
> 
> As it is abandoned since 2019 I don't expect any maintenance overhead with a possible patch

If the fix is about updating dependencies (https://github.com/GraxCode/JByteMod-Beta/pull/88), it means will have to do it from time to time or am I wrong?

**Comment by noraj** [comment]
tool abandonned

**Pull request closed without merging**
