### PR TITLE
OpenDoor scanner: update PKGBUILD

### PR DESCRIPTION
**Pull request by stanislav-web**
OpenDoor scanner: update PKGBUILD

### CODE REVIEW

**Comment by noptrix** [comment]
hey. thanks for this. since there are some conflicts, i will merge this manually and close the PR.

**Comment by noptrix** [comment]
can you please check this error: 
``
raise FileSystemError("{0} is not a file ".format(filepath))
src.core.filesystem.exceptions.FileSystemError: /home/noptrix/blackarch/repos/blackarch/packages/opendoor/setup.cfg is not a file

**Comment by stanislav-web** [comment]
Hi, Noptrix ! Could you show me , how do you install this package ?

**Comment by noptrix** [comment]
sure. by simply running 'python2 setup.py buiid'  and 'python2 setup.py install --root=/somewhere' as you can see here: https://github.com/BlackArch/blackarch/blob/eb262f658e8a8988ea1428078a43bf7cf400d35c/packages/opendoor/PKGBUILD

**Comment by noptrix** [comment]
@stanislav-web  hey, any updates on this?

**Comment by stanislav-web** [comment]
Hi! I apologize for the long time absent!
Could you try to install it from setup again:

https://github.com/stanislav-web/OpenDoor/tree/python3

python3 setup.py build && python3 setup.py install

**Comment by noptrix** [comment]
@stanislav-web i will update it soon and let you know

**Comment by stanislav-web** [comment]
Hi, noptrix! My apologies! Please fetch and try again. I hope the build will be done  success 
https://github.com/stanislav-web/OpenDoor/issues/16

**Comment by noptrix** [comment]
@stanislav-web ok, no worries. i will try it and let you know
@vdun yeah, i've removed it. today we gonna release new ISOs again due to perl libraries, which had to be rebuilt. i will then include opendoor and also include it in the ISOs.

**Comment by noptrix** [comment]
@stanislav-web python2 or python3?

**Comment by noptrix** [comment]
@stanislav-web getting this error: `ImportError: No module named parse`

**Comment by stanislav-web** [comment]
python3

**Pull request closed without merging**
