### PR TITLE
creddump rework

### PR DESCRIPTION
**Pull request by noraj**
#2332

### CODE REVIEW

**Comment by noraj** [comment]
PS: I fully tested this change with `blackarch-devtools`

**Comment by noraj** [comment]
Should I add a `provides()` for the 3 scripts?

**Comment by Edu4rdSHL** [comment]
We doesn't want to switch from upstream repos if there isn't *sufficient  reasons* and definitively there aren't. I will take some of your work and update the PKGBUILD.

**Comment by noraj** [comment]
b85c0d1421a8cd018b72cbe47bff9c4222dd06ba

**Pull request closed without merging**
