### PR TITLE
darkarmour fix #3032

### LINKED ISSUE #3032: darkarmour
darkarmour
https://github.com/bats3c/darkarmour

### PR DESCRIPTION
**Pull request by dualfade**
please review --

### CODE REVIEW

**Comment by dualfade** [comment]
I need to fix this. please hold --

**Comment by Edu4rdSHL** [comment]
Please let me know when it's ready for review.

**Comment by aancw** [comment]
Please @dualfade always use one PR. If you have new fix, just commit in the same branch and it will update the PR progress.

**Comment by dualfade** [comment]
They are ready. 2 PR's. This a ref issue most likely.

**Comment by aancw** [comment]
I know, but it's still the same issue for darkarmour. You can commit to this PR branch instead of creating a new one.

**Comment by dualfade** [comment]
Ok I will be careful of that in the future. I didnt think  the ref would cause an issue. However it did. Can I fix ?

**Comment by Edu4rdSHL** [comment]
Hey, no @aancw, as @dualfade is working is the correct way, after all you are adding a new package to BlackArch, doesn't matter if it's as dependency of a new tool or whatever it needs to be in a separate PR for clarity in the commits history when we merge both PRs.

@dualfade is it ready to review?

**Comment by dualfade** [comment]
@Edu4rdSHL  Ok thanks for clarifying. Yes they both are. Thank you.

**Review by Edu4rdSHL — APPROVED** [review]
Thank you, @dualfade !

**Pull request merged**
