### PR TITLE
[WIP] start grabbing some steps for fuzzbunch install

### LINKED ISSUE #2168: [Tool request] fuzzbunch
It's not a easy work but we will add the shadow brokers fuzzbunch tools, https://github.com/misterch0c/shadowbroker/tree/master/windows/fuzzbunch

### PR DESCRIPTION
**Pull request by noraj**
nedd help, packing for wine is a pain

- upstream URL and manual install steps: https://github.com/mdiazcl/fuzzbunch-debian
- wine tricks:
  - https://wiki.archlinux.org/index.php/Wine#Desktop_launcher_menus
  - https://wiki.archlinux.org/index.php/Wine_package_guidelines

closes #2168

### CODE REVIEW

**Comment by mrsmith0x00** [comment]
@noraj please check my suggested solution, and if something is wrong you can revert changes ;)

**Comment by mrsmith0x00** [comment]
@noraj what do you think about changes?

**Comment by noraj** [comment]
> @noraj what do you think about changes?

Th added the command the desktop file that was missing, also this is not working yet.

```
C:\fuzzbunch-debian\windows>python fb.py
Traceback (most recent call last):
  File "fb.py", line 37, in <module>
    from fuzzbunch.edfplugin import EDFPlugin
  File "C:\fuzzbunch-debian\windows\fuzzbunch\edfplugin.py", line 5, in <module>
    import edfexecution
  File "C:\fuzzbunch-debian\windows\fuzzbunch\edfexecution.py", line 30, in <module>
    import win32pipe
ImportError: No module named win32pipe
001f:fixme:msvcrt:__clean_type_info_names_internal (0x1d1b1ee4) stub
001f:fixme:msvcrt:__clean_type_info_names_internal (0x1004ad84) stub
001f:fixme:msvcrt:__clean_type_info_names_internal (0x1e1f9bc8) stub
```

**Comment by noraj** [comment]
I tried a couple of different things to setup wine in defferents order but when inside package() I get:

```
ERROR: ld.so: object 'libfakeroot.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libfakeroot.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
wine: chdir to /tmp/.wine-1000/server-fe00-13e0b8 : No such file or directory
```

Etc `"$pkgdir/usr/share/$pkgname/.wine-fuzzbunch"`.

Manually making the install works, so it's maybe due to the package installing the wine env as root ? https://wiki.winehq.org/FAQ#Should_I_run_Wine_as_root.3F

**Comment by noraj** [comment]
@mrsmith0x00 

You can test the package like that to see if you succeed to build and run it without error:

```
$ ba-dev -b
$ ba-dev -e 'fuzzbunch' -p fuzzbunch-32.2b76c22-1-x86_64.pkg.tar.zst
run: python fb.py                                                                                                                                                                                                                             
Microsoft Windows 6.1.7601                                                                                                                                                                                                                    
                                                                                                                                                                                                                                              
C:\fuzzbunch-debian\windows>python .fb.py
```

**Comment by mrsmith0x00** [comment]
@noraj maybe due to some glibc limitations. I know, already tested, fuzzbunch seems to work now (today I only see some problems with downloading pywin32 from sourceforge, but it's winetricks issue). I think that all is fine now

**Comment by mrsmith0x00** [comment]
@noptrix @Edu4rdSHL @noraj are we fine and can we merge? I think this is a not useless tool :)

**Comment by noraj** [comment]
@mrsmith0x00 No, it's not good yet.

**Comment by mrsmith0x00** [comment]
@noraj what else can we do? It seems to me that trying to move the wine part back into PKGBUILD is a little pointless. Maybe you have some suggestions?

**Comment by noraj** [comment]
If we are not able to 100% package it out of the box, I imagine we would have to add a bunch of `echo` in a post_install hook to say what manual steps are required.

**Comment by mrsmith0x00** [comment]
@noraj I moved all to user -> manually set up wine. Re-check suggestions, please :)

**Comment by Edu4rdSHL** [comment]
Hello guys, thanks! Please add the package to `to-release` list to merge it.

**Comment by mrsmith0x00** [comment]
Hope that everything is fine

**Pull request merged**
