### PR TITLE
Add mubeng tool

### PR DESCRIPTION
**Pull request by dwisiswant0**

### CODE REVIEW

**Comment by Edu4rdSHL** [comment]
Hey @dwisiswant0, thank you. Lmk when it's ready for review.

**Comment by aancw** [comment]
Hi @dwisiswant0, I see that you are using go and git. Refer to blackarch pkgbuild template, you can directly use go build and git clone. Prefer to build and compile.

https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-go

**Comment by dwisiswant0** [comment]
> Hi @dwisiswant0, I see that you are using go and git. Refer to blackarch pkgbuild template, you can directly use go build and git clone. Prefer to build and compile, so tar.gz is not needed.
> 
> https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-go

Thanks for your suggestion, @aancw. I prefer manual build from source (for now). But the tool also have self-updating features, so we don't have to worry about that. 

> Hey @dwisiswant0, thank you. Lmk when it's ready for review.

I think I'm done at 6140b639c293f55ed9b3303debf2b3f4f609750b, @Edu4rdSHL.

**Comment by aancw** [comment]
I know, but we prefer using git master branch instead of tar.gz file if possible.
One more thing, did you change objection, lief, ba-zsh? Or it's accidentally?

**Comment by dwisiswant0** [comment]
> I know, but we prefer using git master branch instead of tar.gz file if possible.
> One more thing, did you change objection, lief, ba-zsh? Or it's accidentally? [2af5919](https://github.com/BlackArch/blackarch/commit/2af5919d26396fc0850170e215c4ed1d9886e53a)

It just rebasing from master. :slightly_smiling_face:

**Comment by Edu4rdSHL** [comment]
Hello, package isn't building.

```
└─▶ ba-dev -b
Syncing chroot copy /home/edu4rdshl/blackarch_chroot/blackarch/ with /home/edu4rdshl/blackarch_chroot/root/ ...
Chroot environment is ready!
==> Making package: mubeng 0.4.3-1 (Tue 02 Mar 2021 10:33:41 PM -05)
==> Retrieving sources...
  -> Downloading mubeng-0.4.3.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123  100   123    0     0    364      0 --:--:-- --:--:-- --:--:--   364
100  139k    0  139k    0     0   143k      0 --:--:-- --:--:-- --:--:--  264k
==> Validating source files with sha512sums...
    mubeng-0.4.3.tar.gz ... Passed
==> Making package: mubeng 0.4.3-1 (Tue 02 Mar 2021 10:33:44 PM -05)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (5) perl-error-0.17029-2  perl-mailtools-2.21-4  perl-timedate-2.33-2
             git-2.30.1-1  go-2:1.16-1

Total Installed Size:  628.80 MiB

:: Proceed with installation? [Y/n] 
(5/5) checking keys in keyring                     [######################] 100%
(5/5) checking package integrity                   [######################] 100%
(5/5) loading package files                        [######################] 100%
(5/5) checking for file conflicts                  [######################] 100%
(5/5) checking available disk space                [######################] 100%
:: Processing package changes...
(1/5) installing perl-error                        [######################] 100%
(2/5) installing perl-timedate                     [######################] 100%
(3/5) installing perl-mailtools                    [######################] 100%
(4/5) installing git                               [######################] 100%
Optional dependencies for git
    tk: gitk and git gui
    perl-libwww: git svn
    perl-term-readkey: git svn and interactive.singlekey setting
    perl-mime-tools: git send-email
    perl-net-smtp-ssl: git send-email TLS support
    perl-authen-sasl: git send-email TLS support
    perl-mediawiki-api: git mediawiki support
    perl-datetime-format-iso8601: git mediawiki support
    perl-lwp-protocol-https: git mediawiki https support
    perl-cgi: gitweb (web interface) support
    python: git svn & git p4
    subversion: git svn
    org.freedesktop.secrets: keyring credential helper
    libsecret: libsecret credential helper [installed]
(5/5) installing go                                [######################] 100%
:: Running post-transaction hooks...
(1/4) Creating system user accounts...
Creating group git with gid 977.
Creating user git (git daemon user) with uid 977 and gid 977.
(2/4) Reloading system manager configuration...
  Skipped: Current root is not booted.
(3/4) Arming ConditionNeedsUpdate...
(4/4) Warn about old perl modules
==> Retrieving sources...
  -> Found mubeng-0.4.3.tar.gz
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting mubeng-0.4.3.tar.gz with bsdtar
==> Starting build()...
go get .: no package in current directory
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /home/edu4rdshl/blackarch_chroot/blackarch/build
Failed to build the package.
```

**Comment by dwisiswant0** [comment]
I'm missing something for go-get command. Using go-mod instead to download its dependencies (which working well by my side using `makepkg -s`).
It's ready for review, @Edu4rdSHL & @noptrix.

**Comment by Edu4rdSHL** [comment]
Hey @dwisiswant0. Thank you.

**Pull request merged**
