### PR TITLE
Improving ruby-based packages

### LINKED ISSUE #1225: [conflict] 'ssrf-proxy' and 'yawast'
Hi,

  I'm an archlinux user with blackarch repo enabled and most of the tools installed.
Todays update is adding new tools to my system, but I'm getting transaction
commit fail due to 'conflicting files'. 

  The packages in question are: '**ssrf-proxy**' and '**yawast**':

> $ pacaur -Si ssrf-proxy
> Repository      : blackarch
> Name            : ssrf-proxy
> Version         : 224.2e4c4a7-1
> Description     : Facilitates tunneling HTTP communications through servers vulnerable to Server-Side Request Forgery.
> Architecture    : any
> URL             : https://github.com/bcoles/ssrf_proxy
> Licenses        : MIT
> Groups          : blackarch  blackarch-proxy  blackarch-tunnel
> Provides        : None
> Depends On      : ruby  ruby-bundler
> Optional Deps   : None
> Conflicts With  : None
> Replaces        : None
> Download Size   : 943.43 KiB
> Installed Size  : 3474.00 KiB
> Packager        : Levon Kayan <noptrix@nullsecurity.net>
> Build Date      : Sun 06 Nov 2016 11:56:49 AM EET
> Validated By    : MD5 Sum  SHA-256 Sum  Signature
> 
> [lordy@beast: ~]
> $ pacaur -Si yawast
> Repository      : blackarch
> Name            : yawast
> Version         : 327.b6e39f8-1
> Description     : The YAWAST Antecedent Web Application Security Toolkit.
> Architecture    : x86_64
> URL             : https://github.com/adamcaudill/yawast
> Licenses        : BSD
> Groups          : blackarch  blackarch-webapp  blackarch-scanner  blackarch-fuzzer
> Provides        : None
> Depends On      : ruby
> Optional Deps   : None
> Conflicts With  : None
> Replaces        : None
> Download Size   : 2.34 MiB
> Installed Size  : 8.78 MiB
> Packager        : Levon Kayan <noptrix@nullsecurity.net>
> Build Date      : Sun 13 Nov 2016 02:53:21 PM EET
> Validated By    : MD5 Sum  SHA-256 Sum  Signature

  And the conflicting files:

> /usr/lib/ruby/gems/2.3.0/cache/colorize-0.8.1.gem exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/cache/ipaddress-0.8.3.gem exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/colorize-0.8.1/CHANGELOG exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/colorize-0.8.1/LICENSE exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/colorize-0.8.1/README.md exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/colorize-0.8.1/Rakefile exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/colorize-0.8.1/colorize.gemspec exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/colorize-0.8.1/lib/colorize.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/colorize-0.8.1/lib/colorize/class_methods.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/colorize-0.8.1/lib/colorize/instance_methods.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/colorize-0.8.1/lib/colorized_string.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/colorize-0.8.1/test/test_colorize.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/.document exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/.gitignore exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/.rock.yml exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/CHANGELOG.rdoc exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/Gemfile exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/LICENSE.txt exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/README.rdoc exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/Rakefile exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/ipaddress.gemspec exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/lib/ipaddress.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/lib/ipaddress/ipv4.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/lib/ipaddress/ipv6.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/lib/ipaddress/mongoid.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/lib/ipaddress/prefix.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/lib/ipaddress/version.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/test/ipaddress/ipv4_test.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/test/ipaddress/ipv6_test.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/test/ipaddress/mongoid_test.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/test/ipaddress/prefix_test.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/test/ipaddress_test.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/gems/ipaddress-0.8.3/test/test_helper.rb exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/specifications/colorize-0.8.1.gemspec exists in both 'ssrf-proxy' and 'yawast'
> /usr/lib/ruby/gems/2.3.0/specifications/ipaddress-0.8.3.gemspec exists in both 'ssrf-proxy' and 'yawast'

Regards,
JNB

### PR DESCRIPTION
**Pull request by lsfxz**
As promised here's my attempt to improve the ruby-based packages of blackarch.
Should fix #1225. Mostly focused on the gem-based packages, most of the others could probably remain as they are. All the non-git gem-based packages can relatively conveniently be managed using [quarry](https://github.com/lsfxz/quarry/tree/blackarch), for the git-based gems manual intervention is still neccessary, I think.

I didn't touch dradis(-ce) and beef yet. It probably would be hard to maintain them using ruby-packages as they have quite a lot and versioned dependencies. Instead it would probably be easiest to keep the post-install-way, but also add a post-remove function so the directories of the dependencies won't remain after removing the packages. I'll look into that soon.

Where I've changed  the package-prefix I've also added "replace", "provides" (for backwards compatibility until I correct the packages which have dependencies for the original ones) and "conflicts", so they should be installed correctly when invoking `pacman -Syu`.

As explained in #1225 I couldn't completely test if everything works as it should, nor the x86_32 and ARM compatibilty. If I'm just missing a relatively easy way to build blackarch myself I'll happily try to ensure everything works if someone can nudge me in the right direction.

### CODE REVIEW

**Comment by noptrix** [comment]
thanks a lot! i will review it today and merge in your request.

**Comment by noptrix** [comment]
hey. really appreciated. thanks a lot for your work. we are currently updating all packages and release the new ISOs soon. once we finished that we can review your work here and merge in your requests. though, i can remember that we got rid of adding ruby-packages or at least tried to avoid it since ruby's lib management fucked up the tools a every time we updated the libs... that was the reason we used to stick with 'bundle install' in /usr/share/somerubybasedpackage/. it was really a  mess :/ so we have to see how we can merge in your stuff.

**Comment by lsfxz** [comment]
Good to know. I'll try to keep up with the changes so as to keep it as mergeable as possible.

The modified quarry _should_ make it relatively painless to keep up with the ruby dependencies, at least for the gem-based ruby packages (which most of them are). There are a few where manual intervention might be neccessary, though, and for those with heavy bundle-usage and many (versioned) dependencies [read: dradis, beef] I stuck to the bundle-method anyway – only adding post_remove() to keep leftover files from piling up when removing a package.

In the meantime I've tested whether the update/replacement process would work (it does) and started to look at ARM compatibility: So far it seems I'll only need a few modifications in quarry to get everything to build properly, and the few cases of native extensions I've already looked at seem to build fine that way.

By the way: I'd be totally willing to keep on updating the ruby-based packages in the future as well, if you'd like – I've got everything in place already anyway, so why not, and I intend to keep on using blackarch, too.

**Comment by noptrix** [comment]
thanks a lot! we've just released the new ISOs. we would now start reviewing your stuff here and try to merge in :)

**Comment by lsfxz** [comment]
I've still been working on it and have now successfully put my changes (and those of my file-conflicts based PR) in a repository, which makes it possible to `pacman -S blackarch` without getting any conflicts (almost: the b2sum package still exists in the blackarch repos, which I can't override with a repo, of course, so until then a `--ignore b2sum` is still needed) on a fresh system, or to `-Syu` successfully without any `--force`.
Built in a clean chroot.

That way I can happily use a "cleaner" blackarch until you've reviewed my stuff ;)

If it'd help you make your decision, it should work if put above [blackarch]:
```
[obsidian]
SigLevel = Never
Server = https://sfho.net/obsidian/x86_64/

[blackarch]
Server = https://www.mirrorservice.org/sites/blackarch.org/blackarch/$repo/os/$arch
```
It is on a server with relatively low traffic contingent so this is truly only for testing.
Only x86_64 yet, because I didn't yet have time to mess around with cross compiling.

**Comment by lsfxz** [comment]
Since I'm looking through the open issues: This should at least fix #1234, maybe even #1262 (whatever the error there exactly is – but my beef seems to work).

**Comment by lsfxz** [comment]
I hope you're not in a hurry merging this – Ruby 2.4 has reached _extra_ and everything's a bit horrible – I'll take that as a good point to take a closer look at quarry again to get the generated PKGBUILDS closer to your style-requirements, look at some other odds and ends and bump it all up to 2.4 (…if possible) in the next days.

**Comment by noptrix** [comment]
:) was about to write you regarding the ruby-2.4 bump...well take your time. we still need to focus on few other things before coming to the ruby parts. but again thanks a lot for your contribution.

**Comment by lsfxz** [comment]
So far the quarry- and PKGBUILD-overhaul is done, currently I'm just waiting for the promised  release of a new version of arachni – currently it has a dependency (msgpack == 0.7) that doesn't seem to build on Ruby 2.4 which I hope will be taken care of with it. Everything else seems to build fine (so far), except for the not directly gem-based packages which I've not yet had time to look at.
If Arachni and Metasploit ( rapid7/metasploit-framework#7814 ) won't work soonish it might be necessary to add a Ruby2.3 package, though.

**Comment by anthraxx** [comment]
@lsfxz metasploit will work soonish, there is also a regular metasploit package in the Arch repositories :wink:

**Comment by lsfxz** [comment]
@anthraxx of course there is – you're doing great work over there ;)

**Comment by lsfxz** [comment]
So, everything _builds_ successfully now. Arachni is back to a state where dependencies are handled by bundler. I've just bumped the problematic gems in the gemspec to newer versions and that way arachni successfully builds and starts – but I couldn't (yet) do further tests on whether it actually completely works or not.
Same goes for most gems: No issues when building, but there needs to be some further testing if they all function properly with Ruby 2.4.

I haven't done anything with metasploit yet – if it would be desirable to have a 2.3-packae while upstream is being worked on I could try to tackle it, otherwise I'd just wait.

**Comment by lsfxz** [comment]
I haven't used IRC for ages :D
But sure, I'll go there.

**Comment by noptrix** [comment]
kewl, let's meet tomorrow in #blackarch channel then on freenode :) time, i would say: like now (8/9pm CET)

**Comment by lsfxz** [comment]
So I guess you were busy – I'll see that I'll be there again to~~morrow~~night :)

**Comment by lsfxz** [comment]
Interest is low, my fork/repo now also includes other non-blackarch-packages as well, so I'll just close this, I guess – if there's ever the need to actually do this a fresh PR might make more sense.

**Pull request closed without merging**
