### PR TITLE
[WIP] updating mobsf

### PR DESCRIPTION
**Pull request by noraj**
this is a work in progress, help wanted

- mobsf was in a very old version (lot of changes between `489.712e800` and `775.8fcebdf`)
- I updated dependencies but we still need proper packages for
  - [x] CapFuzz https://github.com/BlackArch/blackarch/issues/2142
  - [x] pdfkit, PR https://github.com/BlackArch/blackarch/pull/2137
  - [x] androguard, PR WIP https://github.com/BlackArch/blackarch/pull/2138
  - [x] biplist, PR https://github.com/BlackArch/blackarch/pull/2140
  - [x] removed configparser, https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/799
- [ ] we also need proper testing of the actual PKGBUILD, i just modified dependencies and reference from `python2` to `python`

### CODE REVIEW

**Comment by noptrix** [comment]
@noraj thanks for your help!

**Comment by Edu4rdSHL** [comment]
I will test the PKGBUILD today and see if it's working well.

**Comment by Edu4rdSHL** [comment]
Hello, @noraj.

I was checking the PKGBUILD today and i found those issues:
1. The file that you tried to execute actually here  https://github.com/BlackArch/blackarch/blob/24e55d9a34ccdf78db9c0549d6fc17b3d78e2812/packages/mobsf/PKGBUILD#L55 
doesn't exist in the package generated for the actual PKGBUILD. You need to execute `run.sh` that's here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/run.sh


2. Running `run.sh` without before running https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/setup.sh also end in a error:

`./run.sh: line 1: venv/bin/activate: No such file or directory`

Then you need to consider the following points to solve it:

1. Create a post_install (see https://wiki.archlinux.org/index.php/PKGBUILD#install) file that allow you to run `setup.sh` when the package is installed.
2. If `run.sh` end in the error mentioned previously, tell to the user that he need to run `setup.sh` before.

Though that the first solution is more appropriate.

Doing the steps mentioned, the package run as expected:

virtualbox_blackarch-linux_10_12_2018_20_03_20

Thank you for all the work, if you have questions or want that I fix the package, let me know.

Regards.

**Comment by noraj** [comment]
@Edu4rdSHL Based on https://hub.docker.com/r/opensecurity/mobile-security-framework-mobsf/~/dockerfile/, we also should add openjdk, git, sqlite3, etc. dependencies

**Comment by noraj** [comment]
@Edu4rdSHL We also need to add a post-install script for db migration and cleanup https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf

**Comment by noptrix** [comment]
yes, please add missing deps and add the post-install things and then we should fine.

**Comment by Edu4rdSHL** [comment]
@noraj can you add the .install file referenced here https://github.com/BlackArch/blackarch/pull/2143/commits/617693981234dd20bcda52b59e2be14552c1f7a2#diff-29cdad700478ff3b297ed69e293ec88fR19? Also, can you use the versioned model instead of the git model? It's more easy for US to maintain/update the package.

**Comment by noraj** [comment]
@noptrix I did it but didn't tested yet.
@Edu4rdSHL I was doing it when you wrote that. Yeah I was thinking about the versioned model but last release is from December 2017, maybe we could create both?

**Comment by Edu4rdSHL** [comment]
@noraj the release is ready. See https://github.com/MobSF/Mobile-Security-Framework-MobSF/releases/tag/v1.0.3Beta

**Comment by noptrix** [comment]
guys, let me know when ready to release. :)

**Comment by Edu4rdSHL** [comment]
I'm going to close it issue today doing the minor missing modifications (versioned model) and verifying that the package works as expected in a clean environment.

**Comment by noraj** [comment]
@Edu4rdSHL Thanks, I'm sorry I didn't have time to do that before you.

**Comment by Edu4rdSHL** [comment]
@noraj thank you for the hard work, see my fixes in https://github.com/BlackArch/blackarch/commit/89cf2bf6e98a4984750844302f512694e75b6060, and again, thanks a lot.

**Comment by noraj** [comment]
@Edu4rdSHL You're welcome, thank you too for maintaining Blackarck. I'm an offensive security professional and infosec passionate so I'll continue to contribute to Blackarch for the long run.

**Comment by noraj** [comment]
@Edu4rdSHL Taling about 89cf2bf, I'm curious where did you find all new dependencies?

Also I saw you changed the `post_install` to call `setup.sh`, but calling it will exec `python3 -m pip install virtualenv` and `pip install -r requirements.txt` again. Is it not a risk to mess with the system pip or install of pyenv? I read a ton of times on arch forums not to use pip package but rather rely on arch ones as it is far easier to maintain and less a source of conflict.

**Comment by noptrix** [comment]
@noraj thanks for pointing out the post_install thing. you are right as we should not call pip in this case. i've removed the install file.

**Comment by noraj** [comment]
@noptrix You can't just remove `packages/mobsf/mobsf.install` in 1e961acd655cd732016c60382af5296025a180ee, we still need `post_install` and `post_upgrade` steps. Where `pip install` is unneeded, but there is still:

- `virtualenv` stuuf that is maybe needed
- clean.sh : needed for upgrade
- migrations : needed for upgrade and post install

**Comment by Edu4rdSHL** [comment]
@noraj fixed in 4653359cf

**Comment by noptrix** [comment]
thanks @Edu4rdSHL

**Comment by noraj** [comment]
```
sudo pacman -S mobsf                                                                                                                      
resolving dependencies...                                                                                                                              
looking for conflicting packages...                                                                                                                    
                                                                                                                                                       
Packages (1) mobsf-1:1.0.3Beta-3                                                                                                                       
                                                                                                                                                       
Total Installed Size:  122,71 MiB                                                                                                                      
                                                                                                                                                       
:: Proceed with installation? [Y/n] y                                                                                                                  
(1/1) checking keys in keyring                                                             [#####################################################] 100%
(1/1) checking package integrity                                                           [#####################################################] 100%
(1/1) loading package files                                                                [#####################################################] 100%
(1/1) checking for file conflicts                                                          [#####################################################] 100%
(1/1) checking available disk space                                                        [#####################################################] 100%
:: Processing package changes...                                                                                                                       
(1/1) installing mobsf                                                                     [#####################################################] 100%
==> Seting up python virtual env                                                                                                                       
Using base prefix '/usr'                                                                                                                               
New python executable in /usr/share/mobsf/venv/bin/python3                                                                                            
Also creating executable in /usr/share/mobsf/venv/bin/python                                                                                          
Installing setuptools, pip, wheel...done.                                                                                                             
/usr/lib/python3.7/site-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's document
ation for alternative uses                                                                                                                            
  import imp                                                                                                                                          
Running virtualenv with interpreter /home/noraj/.pyenv/shims/python3                                                                                  
==> Clean Up                                                                                                                                          
                                                                                                                                                      
=======================MobSF Clean Script for Unix=======================                                                                             
Running this script will delete the Scan database, all files uploaded and generated.
                                                                                                                                                       
Deleting all Uploads                                                                                                                                   
Deleting all Downloads                                                                                                                                 
Deleting Static Analyzer Migrations                                                                                                                    
Deleting Dynamic Analyzer Migrations                                                                                                                   
Deleting MobSF Migrations                                                                                                                              
Deleting python byte code files                                                                                                                        
Deleting temp and log files                                                                                                                            
Deleting DB                                                                                                                                            
Deleting Secret File                                                                                                                                   
Done                                                                                                                                                   
==> Migrating Database if exists                                                                                                                       
Traceback (most recent call last):                                                                                                                     
  File "manage.py", line 8, in <module>                                                                                                                
    from django.core.management import execute_from_command_line                                                                                       
ModuleNotFoundError: No module named 'django'                                                                                                          
Traceback (most recent call last):                                                                                                                     
  File "manage.py", line 8, in <module>                                                                                                                
    from django.core.management import execute_from_command_line                                                                                       
ModuleNotFoundError: No module named 'django'                                                                                                          
Traceback (most recent call last):                                                                                                                     
  File "manage.py", line 8, in <module>                                                                                                                
    from django.core.management import execute_from_command_line                                                                                       
ModuleNotFoundError: No module named 'django'                                                                                                          
==> Installation Complete
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

`python-django` is installed, but since we are in a virtualenv now, we need to do the `pip install -r requirements.txt` to install dependencies inside the virtual env. This is not dangerous for our system as `source venv/bin/activate` should have replaced `pip` with the one in the virtualenv. Else I think all dependencies in `requirements.txt` will miss in the virtualenv.

I don't know if it is better to pip install in the virtualenv or not using the virtualenv.

**Comment by noptrix** [comment]
> ```
> sudo pacman -S mobsf                                                                                                                      
> resolving dependencies...                                                                                                                              
> looking for conflicting packages...                                                                                                                    
>                                                                                                                                                        
> Packages (1) mobsf-1:1.0.3Beta-3                                                                                                                       
>                                                                                                                                                        
> Total Installed Size:  122,71 MiB                                                                                                                      
>                                                                                                                                                        
> :: Proceed with installation? [Y/n] y                                                                                                                  
> (1/1) checking keys in keyring                                                             [#####################################################] 100%
> (1/1) checking package integrity                                                           [#####################################################] 100%
> (1/1) loading package files                                                                [#####################################################] 100%
> (1/1) checking for file conflicts                                                          [#####################################################] 100%
> (1/1) checking available disk space                                                        [#####################################################] 100%
> :: Processing package changes...                                                                                                                       
> (1/1) installing mobsf                                                                     [#####################################################] 100%
> ==> Seting up python virtual env                                                                                                                       
> Using base prefix '/usr'                                                                                                                               
> New python executable in /usr/share/mobsf/venv/bin/python3                                                                                            
> Also creating executable in /usr/share/mobsf/venv/bin/python                                                                                          
> Installing setuptools, pip, wheel...done.                                                                                                             
> /usr/lib/python3.7/site-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's document
> ation for alternative uses                                                                                                                            
>   import imp                                                                                                                                          
> Running virtualenv with interpreter /home/noraj/.pyenv/shims/python3                                                                                  
> ==> Clean Up                                                                                                                                          
>                                                                                                                                                       
> =======================MobSF Clean Script for Unix=======================                                                                             
> Running this script will delete the Scan database, all files uploaded and generated.
>                                                                                                                                                        
> Deleting all Uploads                                                                                                                                   
> Deleting all Downloads                                                                                                                                 
> Deleting Static Analyzer Migrations                                                                                                                    
> Deleting Dynamic Analyzer Migrations                                                                                                                   
> Deleting MobSF Migrations                                                                                                                              
> Deleting python byte code files                                                                                                                        
> Deleting temp and log files                                                                                                                            
> Deleting DB                                                                                                                                            
> Deleting Secret File                                                                                                                                   
> Done                                                                                                                                                   
> ==> Migrating Database if exists                                                                                                                       
> Traceback (most recent call last):                                                                                                                     
>   File "manage.py", line 8, in <module>                                                                                                                
>     from django.core.management import execute_from_command_line                                                                                       
> ModuleNotFoundError: No module named 'django'                                                                                                          
> Traceback (most recent call last):                                                                                                                     
>   File "manage.py", line 8, in <module>                                                                                                                
>     from django.core.management import execute_from_command_line                                                                                       
> ModuleNotFoundError: No module named 'django'                                                                                                          
> Traceback (most recent call last):                                                                                                                     
>   File "manage.py", line 8, in <module>                                                                                                                
>     from django.core.management import execute_from_command_line                                                                                       
> ModuleNotFoundError: No module named 'django'                                                                                                          
> ==> Installation Complete
> :: Running post-transaction hooks...
> (1/1) Arming ConditionNeedsUpdate...
> ```
> `python-django` is installed, but since we are in a virtualenv now, we need to do the `pip install -r requirements.txt` to install dependencies inside the virtual env. This is not dangerous for our system as `source venv/bin/activate` should have replaced `pip` with the one in the virtualenv. Else I think all dependencies in `requirements.txt` will miss in the virtualenv.
> 
> I don't know if it is better to pip install in the virtualenv or not using the virtualenv.

This is what I wante to achieve with removing the install file to not use the virtualenv at all. This is really not necessary since we provide all deps and the correct env. I will remove the virtualenv part. Thanks for letting us know.

**Comment by noptrix** [comment]
@noraj Ok, changes made. Let us know if something is still wrong or missing.

**Pull request merged**
