### PR TITLE
add enum4linux-ng

### PR DESCRIPTION
**Pull request by noraj**
close https://github.com/cddmp/enum4linux-ng/issues/11
close https://github.com/BlackArch/blackarch/issues/2925

### CODE REVIEW

**Review by Edu4rdSHL — APPROVED** [review]

**Comment by Edu4rdSHL** [comment]
Hey @noraj, thank you! I only wonder if `enum4linux-ng` doesn't have any kind of conflicting files with `enum4linux` so that we need to add `conflicts=()` to the PKGBUILD.

**Comment by cddmp** [comment]
@Edu4rdSHL 
There should are no conflicts. enum4linux is Perl while this one is Python. Both don't share files or interact in any way with each other.

**Comment by Edu4rdSHL** [comment]
Hello, @cddmp, thank you for answering so quickly. Merging.

**Comment by noraj** [comment]
Yes no conflict Python/perl + the way it is package even if both wold have been in python there would have been installed in a separate folder with a separate binary name so no worry.

**Comment by cddmp** [comment]
Thanks!

**Pull request merged**
