### PR TITLE
[Tool Request] Added Zracker and See-SURF

### PR DESCRIPTION
**Pull request by devim-stuffs**
**Tools Added : Zracker, See-SURF**

### CODE REVIEW

**Comment by pwnfoo** [comment]
@devim-stuffs Zcracker PR was closed. Do not include it with PR for other tools.

**Comment by devim-stuffs** [comment]
> @devim-stuffs Zcracker PR was closed. Please do not include it with PR for other tools.
> 
> See point number 5 in #2842
> 
> We already have `john`+`zip2john` along with other tools like `fcrackzip`

HEY @pwnfoo
(1) Of Zracker previous PR, as it was closed due to some code considerations, I had already made changes for the same..
(2) As to include it for PR with other tools, I think I should split them..sorry my bad 😔
(3) And for fcrackzip and John, are they working by splitting tasks independently on independent cores as in Zcracker...

Check https://github.com/devim-stuffs/Zracker

All the best 👍

**Comment by devim-stuffs** [comment]
Make sure to check reply from @Edu4rdSHL here: #2894 
😁

**Comment by pwnfoo** [comment]
@devim-stuffs Are you claiming that Zcracker written in Python is faster than `john` and `fcrackzip` which are written in C?

**Comment by devim-stuffs** [comment]
> @devim-stuffs Are you claiming that Zcracker written in Python is faster than `john` and `fcrackzip` which are written in C?

You're getting wrong buddy..
Read here : https://github.com/devim-stuffs/Zracker

**Pull request closed without merging**
