### PR TITLE
Add log4j-bypass.py

### PR DESCRIPTION
**Pull request by cyberqueen-meg**
Hello,

This script tests for log4j vulnerabilities on web URLs and is compatible with BlackArch. Please consider adding it. Thank you!

### CODE REVIEW

**Review by noptrix — CHANGES_REQUESTED** [review]
@cyberqueen-meg thanks a lot for this! could you please adapt your PKGBUILD to our template/style: https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-generic-git - so we use `tabstop=2` and `shiftwidth=2`. we name it `PKGBUILD` and not `PKGBUILD.sh`. A custom BA header is added in each PKGBUILD file. `python3` can be replaced with `python`. `pkgrel` should be initiated with `1`  and should be only positive int (that allows to differentiate between consecutive builds of the same version of a package). cheers

**Comment by cyberqueen-meg** [comment]
Added the changes requested

**Comment by noptrix** [comment]
@cyberqueen-meg nice, thanks a lot. the `...` inside `prepare()` will be removed:) we will do that

**Review by noptrix — APPROVED** [review]

**Comment by noptrix** [comment]
@cyberqueen-meg released. and check our PKGBUILD changes, please (for future PRs): https://github.com/BlackArch/blackarch/commit/b68cee3855950f4e792aa3de8bb414cb5de0e439

**Comment by cyberqueen-meg** [comment]
wonderful, thanks @noptrix! This is my first time building a PKGBUILD so I'm sure I have lots to learn lol

**Comment by noptrix** [comment]
> wonderful, thanks @noptrix! This is my first time building a PKGBUILD so I'm sure I have lots to learn lol

no worries and thanks for your contribution.

**Comment by noptrix** [comment]
@cyberqueen-meg btw, here is a multihreaded version of your tool: http://ix.io/3J01 - i quickly patched it on my local machine. if you add it to your repository we can version bump immediately.

**Comment by cyberqueen-meg** [comment]
adding now, just a second

Thanks!

**Pull request merged**
