### PR TITLE
fixed unix-privesc-check

### PR DESCRIPTION
**Pull request by D3vil0p3r**
Fixed sha512 and binary name that was wrongly `unix-privsc-check`.

### CODE REVIEW

**Review by noraj — COMMENTED** [review]
I don't see a change for the binary name

**Comment by D3vil0p3r** [comment]
> I don't see a change for the binary name

Hey. Try to install the current package. You will see that the binary name is the wrong one. I don't know why, indeed the old PKGBUILD (except for SHA512) seems right.

**Comment by noraj** [comment]
kk so outside the hash it needs a rebuild

**Comment by noptrix** [comment]
@D3vil0p3r thank you - please don't remove the last empty line inside a PKGBUILD.

**Pull request merged**
