### PR TITLE
create python3 biplist package

### PR DESCRIPTION
**Pull request by noraj**

### CODE REVIEW

**Comment by noraj** [comment]
@noptrix for my defense, I copied `python2-biplist` PKGBUILD https://github.com/BlackArch/blackarch/blob/master/packages/python2-biplist/PKGBUILD

**Comment by Edu4rdSHL** [comment]
@noraj why you are not using https://bitbucket.org/wooster/biplist/downloads/biplist-1.0.3.tar.gz instead of pythonhosted files?

**Comment by noraj** [comment]
@Edu4rdSHL No reason.

**Comment by Edu4rdSHL** [comment]
Please update the sha512sums if necessary (I can't be sure if are the same for both sources)

**Comment by noraj** [comment]
@Edu4rdSHL I did checked of course, they are the same.

**Comment by noraj** [comment]
```
wget -O - -o /dev/null https://bitbucket.org/wooster/biplist/downloads/biplist-1.0.3.tar.gz | sha512sum -
186927481229988c713d9bb703115493001b129ed4e540e9a028e99b4f10e1576291c75f98d39b28e04092c14a9c96e4843c1445d9a318ced322323c7c1134b5  -
```

**Pull request merged**
