### PR TITLE
savvycan: add package

### PR DESCRIPTION
**Pull request by D3vil0p3r**
Close https://github.com/BlackArch/blackarch/issues/4291

Merged: https://github.com/collin80/SavvyCAN/pull/854

### CODE REVIEW

**Comment by D3vil0p3r** [comment]
@noptrix SavvyCAN maintainer merged my PR upstream to fix the icon issue https://github.com/collin80/SavvyCAN/pull/854

Feel free to merge this when you are available. Thanks

**Comment by noptrix** [comment]
@D3vil0p3r 
```
==> Starting build()...
Info: creating stash file /home/noptrix/blackarch/repos/blackarch/packages/savvycan/src/SavvyCAN/.qmake.stash
Project ERROR: Unknown module(s) in QT: qml
==> ERROR: A failure occurred in build().
    Aborting...
```
any idea on this?

**Comment by D3vil0p3r** [comment]
Sorry @noptrix can you try to add in `depends` the package `qt5-declarative` and let me know if it builds correctly? Thanks

**Comment by noptrix** [comment]
> Sorry @noptrix can you try to add in `depends` the package `qt5-declarative` and let me know if it builds correctly? Thanks

that worked. thank you. :)

**Pull request merged**
