### PR TITLE
Added UACME

### PR DESCRIPTION
**Pull request by osospeed**

### CODE REVIEW

**Comment by PedroSFreitas** [comment]
@osospeed please, follow the same instruction I gave on this PR https://github.com/BlackArch/blackarch/pull/1924

And Thanks! :+1:

**Comment by osospeed** [comment]
Check again please.

**Comment by PedroSFreitas** [comment]
@osospeed thanks

@noptrix looks good.

**Comment by noptrix** [comment]
thanks a lot to both

**Pull request merged**
