### PR TITLE
dnsrecon: add missing dependency

### PR DESCRIPTION
**Pull request by noraj**
https://github.com/BlackArch/blackarch/issues/2322

### CODE REVIEW

**Comment by noraj** [comment]
Proof: https://github.com/darkoperator/dnsrecon/blob/master/requirements.txt

**Comment by noraj** [comment]
PS : can I be added to the organization ?

**Comment by noptrix** [comment]
@noraj thanks a lot mate! yes sure, but i already sent an invitation. did you get it?!

**Comment by noraj** [comment]
@noptrix No I didn't receive a notification :(

**Comment by Edu4rdSHL** [comment]
You need to check your email.

**Pull request merged**
