### PR TITLE
BlackArch Tunning

### PR DESCRIPTION
**Pull request by 4k4xs4pH1r3**
by 4k4xs4pH1r3

### CODE REVIEW

**Comment by PedroSFreitas** [comment]
First of all, thanks.
But this seems more like a personal customization than something that could be used by anyone. That said, I don't think it should be merged.

@noptrix what do you think?

**Comment by 4k4xs4pH1r3** [comment]
This pull request born from the issues related with network specifically getting up the interfaces; dhcp; wicd; d-bus / NetworkManager. The rest is value added

**Comment by PedroSFreitas** [comment]
"Network getting up" is not an issue, is laziness of people that don't want to read the documentation.
About the value added, true. Good contribution. But as I said, very personal. For instance I wouldn't use any of that setup.
The idea is having the minimum possible related to configuration, so people can set their system the way they want; not the way we think they should.

**Comment by 4k4xs4pH1r3** [comment]
@PedroSFreitas This is the guide in english https://blackarch.org/blackarch-guide-en.pdf ?

Please share me the link where I can found the documentation for my case.

**Comment by PedroSFreitas** [comment]
@4k4xs4pH1r3 thanks for taking the time to contribute, but we decided (as expressed above) that it should not be merged.

**Pull request closed without merging**
