### PR TITLE
create python3 pdfkit package

### PR DESCRIPTION
**Pull request by noraj**

### CODE REVIEW

**Comment by noraj** [comment]
@ikstream right, because I based the PKGBUILD on the python2 version, so the change is also needed here https://github.com/BlackArch/blackarch/pull/2144

**Comment by noptrix** [comment]
@noraj well ok, let me fix these things. you can then see the changes and next time try to keep the same style etc.

**Comment by noptrix** [comment]
@noraj well ok, let me fix these things. you can then see the changes and next time try to keep the same style etc.

**Comment by noptrix** [comment]
@noraj jfyi: https://github.com/BlackArch/blackarch/commit/276553eb4bc5903b39828c3d872312e978028d92

**Comment by noraj** [comment]
@noptrix Ok, my bad.

**Pull request merged**
