### PR TITLE
rustcat: Update binname

### PR DESCRIPTION
**Pull request by robiot**
Changed from rc to rcat to prevent clash with /sbin/rc on openrc systems.

### CODE REVIEW

**Comment by noptrix** [comment]
@robiot hi. why to `rcat`?

**Comment by robiot** [comment]
> @robiot hi. why to `rcat`?

https://github.com/robiot/rustcat/issues/26
I wanted rustcat to work on all systems(even openrc based) with the same executable name. Thats why I changed to rcat instead of rc. This will make it easier to understand since the [documentation](https://github.com/robiot/rustcat/wiki/Basic-Usage) uses rcat.

**Review by noraj — APPROVED** [review]

**Comment by noptrix** [comment]
> > @robiot hi. why to `rcat`?
> 
> [robiot/rustcat#26](https://github.com/robiot/rustcat/issues/26) I wanted rustcat to work on all systems(even openrc based) with the same executable name. Thats why I changed to rcat instead of rc. This will make it easier to understand since the [documentation](https://github.com/robiot/rustcat/wiki/Basic-Usage) uses rcat.

ok

**Comment by noptrix** [comment]
@robiot thank you

**Pull request merged**
