### PR TITLE
rename 'python2-libbde-python' -> 'python2-libbde'

### PR DESCRIPTION
**Pull request by osospeed**

### CODE REVIEW

**Comment by mrsmith0x00** [comment]
@osospeed I fully agree with you, that name without `python` pretty, but this destroy auto-update for this package. I'm sorry, but we can't merge commit.

**Comment by osospeed** [comment]
Sorry, I did not understand exactly what do you mean by 'destroy auto-update'. Can you elaborate more ?

**Comment by mrsmith0x00** [comment]
@osospeed script `version-checker.py` get [python-something] names from `packages/` directory and then connect to PyPI JSON API to check for package updates. If you change package name (both in `pkgname` and in `packages/` directory, script will not find package in PyPI repo.

**Comment by osospeed** [comment]
OK. So if we build it from git instead of pypi, would it then be renamed as 'python2-libbde' ?

**Comment by mrsmith0x00** [comment]
@osospeed btw, why build from git, instead of use from PyPI? It's a bit faster than do `git clone` on each package.

**Pull request closed without merging**
