### PR TITLE
wascan: fix dependency

### PR DESCRIPTION
**Pull request by noraj**
it requires BS3 not 4

BS 4

```
$  wascan --help             
Traceback (most recent call last):
  File "wascan.py", line 37, in <module>
    from lib.handler.crawler import *
  File "/usr/share/wascan/lib/handler/crawler.py", line 10, in <module>
    from lib.request.crawler import SCrawler
  File "/usr/share/wascan/lib/request/crawler.py", line 15, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup
```

BS 3

```
$ wascan --help             
__________________________________________________
 ________ _______ _______                   
|  |  |  |   _   |     __|.----.---.-.-----.
|  |  |  |       |__     ||  __|  _  |     |
|________|___|___|_______||____|___._|__|__|
                                      v0.2.1
      WAScan - Web Application Scanner      
           C0d3n4m3: ATLAS                  
          Momo Outaadi (m4ll0k)             
__________________________________________________

__________________________________________________
 ________ _______ _______                   
|  |  |  |   _   |     __|.----.---.-.-----.
|  |  |  |       |__     ||  __|  _  |     |
|________|___|___|_______||____|___._|__|__|
                                      v0.2.1
      WAScan - Web Application Scanner      
           C0d3n4m3: ATLAS                  
          Momo Outaadi (m4ll0k)             
__________________________________________________

Usage: wascan.py [options]

        -u --url        Target URL (e.g: http://www.site.com)
        -s --scan       Scan options (default=5):

                0 :     Fingerprint (server,waf,cms,...)
                1 :     Attacks (sql,ldap injection,...)
                2 :     Audit (phpinfo,openredirect,...)
                3 :     Bruteforce (dir,file,backup,...)
                4 :     Disclosure (emails,password,...)
                5 :     Full scan (audit,attacks,brute,...)

        -b --brute      Bruteforce hidden parameters (GET only)
        -H --headers    Extra headers (e.g: "Host:site.com")
        -d --data       Data to be sent via POST method
        -m --method     HTTP method, GET or POST
        -h --host       HTTP Host header value
        -R --referer    HTTP Referer header value
        -a --auth       HTTP Basic Authentication (user:pass)
        -A --agent      HTTP User-agent header value
        -r --ragent     Use random User-agent header value
        -c --cookie     HTTP Cookie header value
        -p --proxy      Use a proxy, (host:port)
        -P --proxy-auth Proxy Authentication, (user:pass)
        -t --timeout    Seconds to wait before timeout connection
        -n --redirect   Set redirect target URL False (default=True)
        -v --verbose    Verbosity, print more informations
        -V --version    Show tool version
        -hh --help      Show this help and exit

Examples:

        wascan.py --url http://www.site.com/
        wascan.py --url http://www.site.com/test.php --brute
        wascan.py --url http://www.site.com/ --scan [0,2,4]
        wascan.py --url http://www.site.com/ --auth "admin:1233"
        wascan.py --url http://www.site.com/index.php?id=1 --scan [1,4]
        wascan.py --url http://www.site.com/index.php --data "id=1" --method POST --scan [1,4]
        wascan.py --url http://www.site.com/index.php?id=1 --scan [1,4] --headers "Host: site.com,..."
        wascan.py --url http://www.site.com/ --scan [0,2,4] --proxy 10.10.10.10:80 --proxy-auth "root:1234"

See this page https://github.com/m4ll0k/WAScan for more examples
```

### CODE REVIEW

**Comment by noraj** [comment]
PS : can I be part of blackarch in some way?

**Comment by Edu4rdSHL** [comment]
Some user was reporting that days ago but I can not reproduce it issue in a clean chroot environment, I will check it again.

**Comment by Edu4rdSHL** [comment]
> 
> 
> PS : can I be part of blackarch in some way?

Please join to IRC or Discord channel and send a DM.

**Comment by Edu4rdSHL** [comment]
Also, supposedly you added support for BS4 here https://github.com/m4ll0k/WAScan/pull/61 :p

**Comment by noraj** [comment]
> Some user was reporting that days ago but I can not reproduce it issue in a clean chroot environment, I will check it again.

I don't see it anywhere in dependencies and sub-dependencies, but when installing wascan yesterday it was also adding some python2 backport package, i'll try again on another machine. What the result of your chroot install?
 

> Also, supposedly you added support for BS4 here [m4ll0k/WAScan#61](https://github.com/m4ll0k/WAScan/pull/61) :p

What's wrong with this BS dependency...

**Comment by Edu4rdSHL** [comment]
It's what I go in the chroot envirinment: https://asciinema.org/a/UH9BIVO6sC2jbBWNTKUxYVT2P

**Comment by noraj** [comment]
@Edu4rdSHL Seems to work well with BS4, and that's true that I did the BS4 PR before. It's weird it didn't worked. I'll try again and see if I'm able to reproduce.

**Comment by Edu4rdSHL** [comment]
I will rebuild the package and see if the rebuild works.

**Comment by noptrix** [comment]
@Edu4rdSHL can we merge in?

**Comment by Edu4rdSHL** [comment]
Not yet, we can release the rebuild package, as you can see in https://asciinema.org/a/UH9BIVO6sC2jbBWNTKUxYVT2P I can't reproduce the issue using the actual PKGBUILD, we'll release the package and see if it's fixed.

**Comment by Edu4rdSHL** [comment]
@noraj can you confirm if the issue is fixed?

**Comment by noraj** [comment]
It seems fixed for me

**Comment by Edu4rdSHL** [comment]
Thx.

**Pull request closed without merging**
