### PR TITLE
Update IVRE (version bump + new doc packaging)

### PR DESCRIPTION
**Pull request by p-l-**

### CODE REVIEW

**Comment by p-l-** [comment]
IVRE no longer relies on setuptools (see cea-sec/ivre#678), that's why I have removed it. Or did I miss something?

The brackets existed already. They also exist in IVRE's PKGBUILD from AUR, and I try to minimize the diff between Blackarch and AUR (which makes it easier to update Blackarch when AUR is updated). Is it really annoying for you?

**Comment by Edu4rdSHL** [comment]
>IVRE no longer relies on setuptools (see cea-sec/ivre#678), that's why I have removed it. Or did I miss something?

As note: when you're going to remove some depends or optional depends, please leave a small note in the PR description why you're removing it.

>The brackets existed already. They also exist in IVRE's PKGBUILD from AUR, and I try to minimize the diff between Blackarch and AUR (which makes it easier to update Blackarch when AUR is updated). Is it really annoying for you?

It's in the guidelines of packaging, brackets should only be used when they're required. And respect to setuptools it's fine for me to remove they then. AUR package will work removing brackets without problems, just push there without brackets and you don't need to change anything when updating thr PKGBUILD.

**Comment by p-l-** [comment]
> It's in the guidelines of packaging, brackets should only be used when they're required.

OK. Could you please link to those guidelines? I'd like to check if I am missing more things before updating this file and those in AUR.

**Comment by Edu4rdSHL** [comment]
Please, see our PKGBUILD styles in https://github.com/BlackArch/blackarch-pkgbuilds, for the IVRE package you should use: https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-generic

**Comment by p-l-** [comment]
Thanks a lot, that's helpful!

**Comment by p-l-** [comment]
I'll update this PR and let you know when it is ready.

**Comment by noptrix** [comment]
thanks a lot guys.

**Comment by p-l-** [comment]
Should be OK now. Thanks for your help. I have also removed `epoch=1` since it does not apply to IVRE from what I understand.

**Comment by Edu4rdSHL** [comment]
Hello @p-l- , thank you for the changes. Merging.

**Comment by p-l-** [comment]
Thanks!

**Pull request merged**
