### PR TITLE
sleuthkit-java: Fixed jar filepath so that autopsy's symlink would be valid

### LINKED ISSUE #249: Add [nfex].
Homepage: http://code.google.com/p/nfex/

### LINKED ISSUE #2497: Autopsy 4.12 fails to start
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Autopsy 4.12.0 doesn't start.

### Steps to reproduce
- Upgrade to latest autopsy
- Run it
- Notice the crash

**Actual result:** 

```
org.netbeans.InvalidException: StandardModule:org.sleuthkit.autopsy.core jarFile: /opt/autopsy/autopsy/modules/org-sleuthkit-autopsy-core.jar: java.lang.NoClassDefFoundError: org/sleuthkit/datamodel/SleuthkitJNI
```

The requested file is not part of that jar.

**Expected result:**

Autopsy would start.

### Screenshots

autopsy-4 12

### Info for developers

**Device:** Dell XPS 15
**GNU/Linux distribution:** Arch
**Tool version:** 4.12

I'm still investigating a bit but I'm about to give up.

### PR DESCRIPTION
**Pull request by obilodeau**
Fixes #2497

### CODE REVIEW

**Comment by obilodeau** [comment]
As described in #2497, the symlink from autopsy's package is:

```
ls -l /opt/autopsy/autopsy/modules/ext/sleuthkit-postgresql-4.6.7.jar 
lrwxrwxrwx 1 root root 35 Oct  9 19:33 /opt/autopsy/autopsy/modules/ext/sleuthkit-postgresql-4.6.7.jar -> /usr/share/java/sleuthkit-4.6.7.jar
```

However, without the patch `sleuthkit-java` install the jar as:

```
$ pacman -Ql sleuthkit-java
sleuthkit-java /usr/
sleuthkit-java /usr/share/
sleuthkit-java /usr/share/java/
sleuthkit-java /usr/share/java/sleuthkit-java-4.6.7.jar
```

You can see that it was intended to go as `/usr/share/java/sleuthkit-<version>.jar` due to the use of  `$_pkgname` already. So instead of changing the autopsy symbolic link, I think updating the destination of the sleuthkit-java jar is what the original packager intended to do.

**Comment by Edu4rdSHL** [comment]
Thanks for the PR, please increase the pkgrel as long as the pkgver isn't increased.

**Comment by Edu4rdSHL** [comment]
@obilodeau thanks again, I'm going to do it for you.

**Comment by obilodeau** [comment]
> Thanks for the PR, please increase the pkgrel as long as the pkgver isn't increased.

True! I forgot. Thanks for doing it for me.

**Pull request merged**
