### PR TITLE
add exe2hex

### PR DESCRIPTION
**Pull request by D3vil0p3r**
Convert a Windows PE executable file to a batch file and vice versa. Ref:  https://www.kali.org/tools/exe2hexbat/
https://github.com/g0tmi1k/exe2hex/

### CODE REVIEW

**Comment by noptrix** [comment]
@D3vil0p3r thanks for this. two things: why do we rename the package name? It shall stay like the original `exe2hex` unless file/package conflict happenes. is the `pkgdesc` accurate? i haven't checked the github page of `exe2hex`.

**Comment by D3vil0p3r** [comment]
Thank you for the comment @noptrix 
I choose that pattern because it is the same used in Kali: https://www.kali.org/tools/exe2hexbat/

But if you agree, we can use exe2hex has pkg name.

**Comment by noptrix** [comment]
> Thank you for the comment @noptrix I choose that pattern because it is the same used in Kali: https://www.kali.org/tools/exe2hexbat/
> 
> But if you agree, we can use exe2hex has pkg name.

oh, i see. well, we don't care about kali tbh... let's stick with its original name, since i don't see any packages which might conflict with that. :) also, please always add an empty line at the end of a `PKGBUILD` file, e.g. always a `\n`.

**Comment by D3vil0p3r** [comment]
> > Thank you for the comment @noptrix I choose that pattern because it is the same used in Kali: https://www.kali.org/tools/exe2hexbat/
> > But if you agree, we can use exe2hex has pkg name.
> 
> oh, i see. well, we don't care about kali tbh... let's stick with its original name, since i don't see any packages which might conflict with that. :) also, please always add an empty line at the end of a `PKGBUILD` file, e.g. always a `\n`.

I agree. I changed the pkgname by the original one and added final `\n`.

**Review by noraj — APPROVED** [review]
LGTM

**Comment by noptrix** [comment]
@D3vil0p3r thanks!

**Pull request merged**
