### PR TITLE
paru: Version bump

### PR DESCRIPTION
**Pull request by ikstream**
Signed-off-by: Stefan Venz <stefan.venz@protonmail.com>

### CODE REVIEW

**Review by noraj — APPROVED** [review]
LGTM but shouldn't we drop paru cf. https://github.com/BlackArch/blackarch/issues/3572?

**Comment by ikstream** [comment]
Why should we drop it. I saw, that there hasn't been an update from our side for a while, but i prefer it over yay.

**Comment by noraj** [comment]
> Why should we drop it. I saw, that there hasn't been an update from our side for a while, but i prefer it over yay.

It's a pacman wrapper not an infosec tool, people can already install it from AUR why package it in BA?

**Comment by ikstream** [comment]
same goes for yay. But it provides a certain ease of usage and doesn't require people to retrieve the PKGBUILD from AUR and build it

**Pull request merged**
