### PR TITLE
Fix major bug

### PR DESCRIPTION
**Pull request by staz0t**
Fixed major logic bug in the latest release

### CODE REVIEW

**Comment by staz0t** [comment]
Hey,
But i have released a separate package for this in my GitHub since it was a major fix. You can see 2 releases in hashcatch's releases. So, should I still keep $pkgrel as 1?

**Comment by noptrix** [comment]
> Hey,
> But i have released a separate package for this in my GitHub since it was a major fix. You can see 2 releases in hashcatch's releases. So, should I still keep $pkgrel as 1?

yes, please. this hasn't anything to do with your releases. it has to do with blackarch.db

**Comment by staz0t** [comment]
Done, I've made the changes. Just out of curiosity, when does one increase the pkgrel?

**Comment by noptrix** [comment]
> Done, I've made the changes. Just out of curiosity, when does one increase the pkgrel?

when you for example change something in the pkgbuild only to fix the install but the version (pkgver) didn't change at all.

**Comment by staz0t** [comment]
Got it, thanks!

**Pull request merged**
