### PR TITLE
blackarch-keyring: Added pacman hook

### PR DESCRIPTION
**Pull request by net-wayfarer**
Installs blackarch-key.hook into /etc/pacman.d/hooks so that the keys in
blackarch-keyring gets reinstated whenever archlinux-keyring is updated.

CC @sepehrdaddev @noptrix

### CODE REVIEW

**Comment by net-wayfarer** [comment]
Hi, recently I have discovered a way to fix `chipsec` package. Here was the issue if installed and ran as-is (in DKMS log):
```
DKMS make.log for chipsec-1070.7966175 for kernel 5.10.13-arch1-2 (x86_64)
Sun 07 Feb 2021 23:21:53 AEST
make: Entering directory '/var/lib/dkms/chipsec/1070.7966175/build'
Unable to find the Linux source tree.
make: *** [Makefile:20: check_kernel_dir] Error 1
make: Leaving directory '/var/lib/dkms/chipsec/1070.7966175/build'
```
The probable problem with `Makefile` is the invocation `uname -r` in which it does not detect `linux-headers` package for instance when `linux` is installed, and instead exits with an error that indicates the headers cannot be found. 

So the workaround this is to make use of variables (found on some other project which uses DKMS). This should then make the issue with the building process like this,
```
DKMS make.log for chipsec-1070.7966175 for kernel 5.10.13-arch1-2 (x86_64)
Sun 07 Feb 2021 23:11:46 AEST
make: Entering directory '/var/lib/dkms/chipsec/1070.7966175/build'
make -C /lib/modules/5.10.13-arch1-2/build M=/var/lib/dkms/chipsec/1070.7966175/build clean
make[1]: Entering directory '/var/lib/dkms/chipsec/1070.7966175/build'
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Leaving directory '/usr/lib/modules/5.10.13-arch1-2/build'
rm -f amd64/cpu.o
nasm -f elf64 -o amd64/cpu.o amd64/cpu.asm
touch amd64/.cpu.o.cmd
make[1]: Entering directory '/var/lib/dkms/chipsec/1070.7966175/build'
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
  CC [M]  /var/lib/dkms/chipsec/1070.7966175/build/chipsec_km.o
/var/lib/dkms/chipsec/1070.7966175/build/chipsec_km.c: In function ‘chipsec_lookup_name’:
/var/lib/dkms/chipsec/1070.7966175/build/chipsec_km.c:1723:10: error: implicit declaration of function ‘get_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
 1723 |  oldfs = get_fs();
      |          ^~~~~~
      |          sget_fc
/var/lib/dkms/chipsec/1070.7966175/build/chipsec_km.c:1723:10: error: incompatible types when assigning to type ‘mm_segment_t’ from type ‘int’
/var/lib/dkms/chipsec/1070.7966175/build/chipsec_km.c:1724:2: error: implicit declaration of function ‘set_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
 1724 |  set_fs (KERNEL_DS);
      |  ^~~~~~
      |  sget_fc
/var/lib/dkms/chipsec/1070.7966175/build/chipsec_km.c:1724:10: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
 1724 |  set_fs (KERNEL_DS);
      |          ^~~~~~~~~
      |          KERNFS_NS
/var/lib/dkms/chipsec/1070.7966175/build/chipsec_km.c:1724:10: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/chipsec/1070.7966175/build/chipsec_km.c:1751:10: error: incompatible types when assigning to type ‘mm_segment_t’ from type ‘int’
 1751 |  oldfs = get_fs();
      |          ^~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/chipsec/1070.7966175/build/chipsec_km.o] Error 1
make[1]: *** [Makefile:1805: /var/lib/dkms/chipsec/1070.7966175/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.10.13-arch1-2/build'
make: *** [Makefile:33: chipsec] Error 2
make: Leaving directory '/var/lib/dkms/chipsec/1070.7966175/build'
```
Thus, be having the same issue as per [this link](https://github.com/chipsec/chipsec/issues/1086)

I am also willing to suspect `tyton` package could probably benefit from this sort of implementation as well.

**Review by ikstream — CHANGES_REQUESTED** [review]
Please don't add curly braces where they aren't needed and follow our packaging style

I don't see how the chipsec package is related to the keyring hook. Please open a pull request per feature you want to add.

**Comment by net-wayfarer** [comment]
> Please don't add curly braces where they aren't needed and follow our packaging style
> 
> I don't see how the chipsec package is related to the keyring hook. Please open a pull request per feature you want to add.

Understood, will omit adding curly braces in the future with PRs.

Yeah the chipsec package is separate. Not sure how am I supposed to do a separate PR as it is my first time doing that.

**Comment by Edu4rdSHL** [comment]
You can just use `git revert` to revert the commit where you have added the chipsec package files and then continue as usual.

**Pull request closed without merging**
