### PR TITLE
weevely - change the script wrapper

### PR DESCRIPTION
**Pull request by noraj**
fix https://github.com/epinna/weevely3/issues/98

### CODE REVIEW

**Comment by Edu4rdSHL** [comment]
You can't launch the script from other location than where are the core libraries that it requires to run, see https://github.com/epinna/weevely3/blob/master/weevely.py#L2-L10

**Comment by noraj** [comment]
@Edu4rdSHL You're right, as an illustration:

```
$ cd /tmp
$ https://github.com/epinna/weevely3.git
$ nvim test.sh
```

Where test.sh

```bash
#!/bin/sh
exec python2 /tmp/weevely3/weevely.py "${@}"
```

Then:

```
$ chmod u+x ./test.sh
$ usage: weevely [-h] {terminal,session,generate} ...

positional arguments:
  {terminal,session,generate}
    terminal            Run terminal or command on the target
    session             Recover an existing session
    generate            Generate new agent

optional arguments:
  -h, --help            show this help message and exit
$ cp ./test.sh ~/
$ cd
$ ./test.sh -h
usage: weevely [-h] {terminal,session,generate} ...

positional arguments:
  {terminal,session,generate}
    terminal            Run terminal or command on the target
    session             Recover an existing session
    generate            Generate new agent

optional arguments:
  -h, --help            show this help message and exit
```

I can call the script from wherever I want. I think the python import system solves this.

**Comment by noraj** [comment]
PS : in the new commit I added a missing dependency, please can you re-open and merge ?

**Comment by noptrix** [comment]
thanks a lot guys.

**Comment by Edu4rdSHL** [comment]
@noraj thank you :)

**Pull request merged**
