### PR TITLE
stegoveritas: update + venv

### PR DESCRIPTION
**Pull request by noraj**
- [x] update from v1.5 to v1.7
- [x] package in a virtual environment to avoid conflict between python-magic and python-python-magic
- [ ] @noptrix can we "remove" python-python-magic if noting else is using it?
- [ ] wait for https://github.com/bannsec/stegoVeritas/pull/27 to be merged in order to fix the major relative import issue

### CODE REVIEW

**Comment by noptrix** [comment]
> * [x]  update from v1.5 to v1.7
> * [x]  package in a virtual environment to avoid conflict between python-magic and python-python-magic
> * [ ]  @noptrix can we "remove" python-python-magic if noting else is using it?
nope. this is used by peframe and viper. :(
> * [ ]  wait for [bannsec/stegoVeritas#27](https://github.com/bannsec/stegoVeritas/pull/27) to be merged in order to fix the major relative import issue

**Comment by noraj** [comment]
>     * this is used by peframe and viper. :(

So we would need to package them in a virtual env too?

**Comment by noptrix** [comment]
> > ```
> > * this is used by peframe and viper. :(
> > ```
> 
> So we would need to package them in a virtual env too?

i think so, yes :( is the current stegoveritas version not working?

**Comment by noraj** [comment]
> is the current stegoveritas version not working?

The one currently in repo is not working, and the one on this PR not either until upstream merge my PR for relative import.

**Comment by noptrix** [comment]
> > is the current stegoveritas version not working?
> 
> The one currently in repo is not working, and the one on this PR not either until upstream merge my PR for relative import.

damn... ok let's wait then. thanks a lot and hit me up once they merged your PR in. :)

**Comment by noraj** [comment]
> damn... ok let's wait then. thanks a lot and hit me up once they merged your PR in. :)

Based on this answer https://github.com/bannsec/stegoVeritas/pull/27#issuecomment-623127234 I fear the upstream author will not want to merge my PR.

As we can't fix the tools if the project owner doesn't want to and we won't be able to maintain a patch for 30+ relative imports in 10+ files over time, I fear we will be forced to remove stegoVeritas from our repository.

But I just answer him so maybe he will change is mind and merge the PR.

**Comment by noraj** [comment]
@noptrix https://github.com/bannsec/stegoVeritas/pull/27#issuecomment-623207689, I tried many way to package this tool in a virtual python environment without having to patch relative import without success. Maybe you'll be better at this. Python dependencies and build ecosystem is a nightmare (at least for me).

**Comment by noptrix** [comment]
> @noptrix [bannsec/stegoVeritas#27 (comment)](https://github.com/bannsec/stegoVeritas/pull/27#issuecomment-623207689), I tried many way to package this tool in a virtual python environment without having to patch relative import without success. Maybe you'll be better at this. Python dependencies and build ecosystem is a nightmare (at least for me).

ok, no problem. let me try to fix this. and thanks for your work! closing this PR here

**Comment by noraj** [comment]
Yup the discussion is going nowhere there https://github.com/bannsec/stegoVeritas/pull/27#issuecomment-623577841. I think he really doesn't understand.

**Pull request closed without merging**
