### PR TITLE
puremagic: initial commit

### PR DESCRIPTION
**Pull request by D4imyo**
a tool dependency.
i am aware of that the library license is MIT and should be installed, but i am confused where to write the install command

### CODE REVIEW

**Comment by noraj** [comment]
>  i am aware of that the library license is MIT and should be installed, but i am confused where to write the install command

once in each `package_()`

**Comment by D4imyo** [comment]
so for package_python2-puremagic() :
install -Dm 644 LICENSE "$pkgdir/usr/share/liceenses/python2-puremagic/LICENSE" ?

**Comment by noraj** [comment]
> so for package_python2-puremagic() :
> install -Dm 644 LICENSE "$pkgdir/usr/share/licenses/python2-puremagic/LICENSE" ?

Yes and the same for py3

**Comment by noptrix** [comment]
thank you @D4imyo

**Pull request merged**
