### PR TITLE
fix broken groups [Fixes blackarch-site #48]

### PR DESCRIPTION
**Pull request by marceloneil**
Fixes https://github.com/BlackArch/blackarch-site/issues/48

I fixed the PKGBUILDs for cudahashcat, libewf, truecrack and vmcloak to have the correct links on the website

### CODE REVIEW

**Comment by noptrix** [comment]
thanks a lot for this! some of them have been intentionally removed from the 'blackarch' group as they are too big and one can still install it by calling 'pacman -S truecrack'. but i will use the other fixes from you and close this PR here. thx again

**Comment by marceloneil** [comment]
Awesome!

**Comment by marceloneil** [comment]
Also @noptrix, make sure you check out https://github.com/BlackArch/blackarch-site/issues/48 for the other website bugs.

**Comment by noptrix** [comment]
@marceloneil  thanks for pointing out, i will make sure to check that.

**Pull request closed without merging**
