### PR TITLE
hostapd-wpe: version bump

### PR DESCRIPTION
**Pull request by D3vil0p3r**
Close https://github.com/BlackArch/blackarch/issues/3980

### CODE REVIEW

**Comment by noptrix** [comment]
@D3vil0p3r thanks!

**Comment by noptrix** [comment]
@D3vil0p3r 
```
patching file hostapd-2.11-wpe.patch
Hunk #6 FAILED at 3611.
1 out of 9 hunks FAILED -- saving rejects to file hostapd-2.11-wpe.patch.rej
```

**Comment by D3vil0p3r** [comment]
Mmm I tested it on clean chroot... Let me give a look and I will update you

**Comment by noptrix** [comment]
https://github.com/BlackArch/blackarch/commit/2aeb0876976a069a54edc4cd076c6a5925d9c810

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r
> ```
> patching file hostapd-2.11-wpe.patch
> Hunk #6 FAILED at 3611.
> 1 out of 9 hunks FAILED -- saving rejects to file hostapd-2.11-wpe.patch.rej
> ```
> ok, fixed it...
> also, could you please consider to follow our guidelines and styles for PKGBUILD as strictly as possible? please check my last changes on this package. please use the templates.

Sure. Thank you for the fix

**Comment by noptrix** [comment]
thanks for your contribution. it helps a lot. but please try to keep following our style :) cheers

**Pull request merged**
