### PR TITLE
jwt_tool: new tool

### PR DESCRIPTION
**Pull request by noraj**
for #2511

### CODE REVIEW

**Comment by Edu4rdSHL** [comment]
> I don't think you can do install -Dm 755 jwt_tool.py "$pkgdir/usr/bin/$pkgname" withotu creating the directory before install -dm 755 "$pkgdir/usr/bin"

You can, when using `-D` it creates the directory automatically.

> The chmod +x "$pkgdir/usr/bin/$pkgname" is still required.

It isn't because you're using `-m 755` (the permissions of the file will be 755).

**Comment by noraj** [comment]
> It isn't because you're using `-m 755` (the permissions of the file will be 755).

Yeah I figure it out myself just after writing this :laughing:

**Comment by noraj** [comment]
```
$  ba-dev -b
$ ba-dev -t -p jwt_tool-27.cef1013-1-any.pkg.tar.zst -e jwt_tool eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

Test :heavy_check_mark:

**Comment by Edu4rdSHL** [comment]
Hey @noraj, thanks a lot!

**Pull request merged**
