### PR TITLE
airgeddon package modified to fix some new dependencies

### PR DESCRIPTION
**Pull request by OscarAkaElvis**
airgeddon package modified to fix some new dependencies

### CODE REVIEW

**Comment by OscarAkaElvis** [comment]
I forgot one thing... I'll do another PR

**Comment by Edu4rdSHL** [comment]
Hello guy, please can you increase pkgrel and pkgver (if necessary)? If not, please let me know to do that myself.

Thanks a lot.

**Comment by Edu4rdSHL** [comment]
> 
> 
> I forgot one thing... I'll do another PR

You can modify your actual PR.

**Comment by OscarAkaElvis** [comment]
I don't know how to modify the pkgver var... what to set there... is done automatically? doing what process?

Regarding the modification of the PR... that could be nice but I don't know how... What I'm doing is forking again to do it in one commit. Guide me if you want to modify this... all I need to modify (i forgot it) is to change the line `sed -i 's|AIRGEDDON_AUTO_UPDATE=true|AIRGEDDON_AUTO_UPDATE=false|' airgeddon.sh`  . Now it is applied to different file ".airgeddonrc"

**Comment by Edu4rdSHL** [comment]
Hello, you can just go to "Files changed" tab inside the PR (here) and clic in the pen to modify what you want. The pkgrel just increase by ++, example, if it's in 1, you should increase it to 2.

**Comment by OscarAkaElvis** [comment]
I did the fix part... regarding the version... this is the actual number `pkgver=1551.13b42c3` ... should it be for example `pkgver=1552.13b42c3`? just replacing 1551 by 1552

**Comment by Edu4rdSHL** [comment]
Hello, no worries, I will do it for you before merging and then you will see how to set it. I recommend to you reading the ArchWiki article to know what are each variable. https://wiki.archlinux.org/index.php/PKGBUILD

**Comment by OscarAkaElvis** [comment]
Ok I will. I usually contact noptrix by IRC just to say "hi, new airgeddon version available" and he does the rest... but this time so much changes and I decided to do the PR. I'll check your commit to see how to increase the number correctly. Thanks.

**Comment by Edu4rdSHL** [comment]
See https://github.com/BlackArch/blackarch/commit/7fee42045d046942a91124cb8653a0337ffab335

**Comment by OscarAkaElvis** [comment]
Yeah I did but pkgrel is useful for this case only... a review of the same package version. What to do on next pull request for a new version? how to calculate pkgver? i've read the related part on wiki but is still unclear to me. Anyway, thank you.

**Pull request merged**
