### PR TITLE
cpp2il: add package

### PR DESCRIPTION
**Pull request by astro-angelfish**
I was reverse engineering a unity game and found there's no tool in BlackArch, so I've googled for the tools I need and found this tool called [cpp2il](https://github.com/SamboyCoding/Cpp2IL)
I thought it would be right that put this tool to BlakcArch.
I didn't test this tool yet and original developer says it is still being rewritten, so I think this PR should be a draft.

### CODE REVIEW

**Comment by noptrix** [comment]
@astro-angelfish thank you. one minor thing: could use `tabstop=2/softtabstop=2/shiftwidth=2` rather than `4`?

**Comment by noraj** [comment]
> @astro-angelfish thank you. one minor thing: could use `tabstop=2/softtabstop=2/shiftwidth=2` rather than `4` for our PKGBUILDs?

We could add that to https://github.com/BlackArch/blackarch/blob/master/.editorconfig for **/PKGBUILD ?

**Comment by astro-angelfish** [comment]
> @astro-angelfish thank you. one minor thing: could use `tabstop=2/softtabstop=2/shiftwidth=2` rather than `4` for our PKGBUILDs?

Sorry for the wrong indent. I've already get used to 4 space indents but I fixed it now.

**Comment by noptrix** [comment]
> > @astro-angelfish thank you. one minor thing: could use `tabstop=2/softtabstop=2/shiftwidth=2` rather than `4` for our PKGBUILDs?
> 
> We could add that to https://github.com/BlackArch/blackarch/blob/master/.editorconfig for **/PKGBUILD ?

yep

**Comment by noptrix** [comment]
> > @astro-angelfish thank you. one minor thing: could use `tabstop=2/softtabstop=2/shiftwidth=2` rather than `4` for our PKGBUILDs?
> 
> Sorry for the wrong indent. I've already get used to 4 space indents but I fixed it now.

thank you!

**Pull request merged**
