### PR TITLE
recon-ng version bump to 4.7.1

### PR DESCRIPTION
**Pull request by ChrisFernandez**
recon-ng was outdated and was getting annoying msg to force a switch to ignore this.. so is easier to just bump the version :) so here it is.

### CODE REVIEW

**Comment by noptrix** [comment]
thanks a lot for reporting. we will ignore the pull request though since we already version bumped on our own while we were reading the github email :)

**Comment by ChrisFernandez** [comment]
thats fine.. only that a couple days have passed and i still don't get the update :-1: 
```
[*] Your version of Recon-ng does not match the latest release.
[*] Please update or use the '--no-check' switch to continue using the old version.
[*] Remote version:  4.7.1
[*] Local version:   4.6.3
[rek2@rek2-desktop ~]$ yaourt -Syu
[sudo] password for rek2: 
:: Sincronizando las bases de datos de los paquetes...
 core está actualizado
 extra está actualizado
 community está actualizado
 multilib está actualizado
 blackarch está actualizado
````

Basically is saying that blackarch is up to date..

**Comment by noptrix** [comment]
weird. which mirror do you use then?

**Comment by noptrix** [comment]
blackarch/recon-ng 1:4.7.1-2 (blackarch blackarch-recon) [installed]
    A full-featured Web Reconnaissance framework written in Python.

**Comment by ChrisFernandez** [comment]
yeah im sure is a mirror issue that may pull changes slowly, I'm at OWASP AppSec 2015 as soon I get home tonight I'll let you know what miriror FYI and change it while I add it :)
Thanks noptrix
Fernandez, Chris.

**Pull request closed without merging**
