### PR TITLE
Spraykatz: Initial commit

### LINKED ISSUE #2626: [Tool request] spraykatz
Tool that is able to retrieve credentials on Windows machines and large Active Directory environments.

Link: https://github.com/aas-n/spraykatz

### PR DESCRIPTION
**Pull request by sachinkamath**
This PR adds https://github.com/aas-n/spraykatz to the package list and fixes #2626

### CODE REVIEW

**Comment by mrsmith0x00** [comment]
@sachinkamath thanks a lot for PR! Please, could you change `source=('git+https://github.com/aas-n/spraykatz.git')` to `source=("git+https://github.com/aas-n/$pkgname.git")`

**Comment by mrsmith0x00** [comment]
@noptrix does everything looks good? Can we merge?

**Comment by sachinkamath** [comment]
@mrsmith0x00 Happy to help!

I've force pushed the source style update

**Comment by noptrix** [comment]
> @noptrix does everything looks good (after fixing source style)? Can we merge?

yep looks good :)

**Comment by noptrix** [comment]
@sachinkamath thank you!

**Pull request merged**
