### PR TITLE
[WIP] Roadtools

### LINKED ISSUE #2885: [Tool Request] ROADtools
- **Name**: ROADtools
- **Source URL**: https://github.com/dirkjanm/ROADtools

### PR DESCRIPTION
**Pull request by noraj**
close  #2885

Still having this error while running

```
$ roadrecon -h
Package roadrecon-39.4929c9d-1-any.pkg.tar.zst installed correctly! Testing it now...                                                                                                                                                        
[root@blackarch /]# roadrecon -h                                                                                                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                                                           
  File "/usr/bin/roadrecon", line 33, in <module>                                                                                                                                                                                            
    sys.exit(load_entry_point('roadrecon==0.9.0', 'console_scripts', 'roadrecon')())                                                                                                                                                         
  File "/usr/bin/roadrecon", line 25, in importlib_load_entry_point                                                                                                                                                                          
    return next(matches).load()                                                                                                                                                                                                              
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load                                                                                                                                                                          
    module = import_module(match.group('module'))                                                                                                                                                                                            
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module                                                                                                                                                                
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                                                                                              
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                                                                                                                                                            
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked                                                                                                                                                                 
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed                                                                                                                                                               
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                                                                                                                                                            
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked                                                                                                                                                                 
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed                                                                                                                                                               
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                                                                                                                                                            
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                                                                                                                                                         
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked                                                                                                                                                                 
ModuleNotFoundError: No module named 'roadtools'
```

### CODE REVIEW

**Comment by noraj** [comment]
@noptrix need help to finish this one

**Comment by Prijey** [comment]
Hello, I have such a mistake, I would appreciate if you can help. Thanks

:error filed retrieving file(download library error)

**Comment by D3vil0p3r** [comment]
Investigated the issue. I tested roadlib directly from source: the setup.py install libs in `/usr/lib/python3.12/site-packages/roadlib-0.27.0-py3.12.egg/roadtools/roadlib/`. It is wrong. The setup must create two separated:
```
/usr/lib/python3.12/site-packages/roadlib-0.27.0-py3.12.egg
/usr/lib/python3.12/site-packages/roadlib/ or /usr/lib/python3.12/site-packages/roadtools/roadlib/
```
In the upstream manner the PKGBUILD does not create the `roadtools/roadlib/`subfolder.

**Comment by D3vil0p3r** [comment]
To not bother you, I created a new PR with fixed PKGBUILD: https://github.com/BlackArch/blackarch/pull/4366

**Comment by D3vil0p3r** [comment]
> To not bother you, I created a new PR with fixed PKGBUILD: #4366

The mentioned PR has been merged. Can you close the current one and also https://github.com/BlackArch/blackarch/issues/2885 ?

**Pull request closed without merging**
