### PR TITLE
added non-deprecated repository and download

### PR DESCRIPTION
**Pull request by josh0xA**
a) Fixed dead repository link
b) Added most recent dripcap version tag 
c) Added proper .tar.gz download link from the archived versions

### CODE REVIEW

**Comment by Edu4rdSHL** [comment]
Hello, please test the packages before pushing commits. The actual PKGBUILD doesn't work, the source is a 404, the package function needs to be update and more. See https://github.com/BlackArch/blackarch/blob/master/docs/HOWTO-DEV.md, if you want to make this process easy, see https://github.com/Edu4rdSHL/blackarch-devtools

**Comment by Edu4rdSHL** [comment]
```
└─▶ ba-dev -b
Syncing chroot copy /home/edu4rdshl/blackarch_chroot/blackarch/ with /home/edu4rdshl/blackarch_chroot/root/ ...
Chroot environment is ready!
==> Making package: dripcap 1:0.3.10-1 (Sat 13 Feb 2021 07:29:52 PM -05)
==> Retrieving sources...
  -> Downloading v0.3.10.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134    0   134    0     0    310      0 --:--:-- --:--:-- --:--:--   310
  0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/orinocoz/dripcap/archive/download/v0.3.10.tar.gz
    Aborting...
==> ERROR: Could not download sources.
Failed to build the package.
```

**Comment by josh0xA** [comment]
> ```
> └─▶ ba-dev -b
> Syncing chroot copy /home/edu4rdshl/blackarch_chroot/blackarch/ with /home/edu4rdshl/blackarch_chroot/root/ ...
> Chroot environment is ready!
> ==> Making package: dripcap 1:0.3.10-1 (Sat 13 Feb 2021 07:29:52 PM -05)
> ==> Retrieving sources...
>   -> Downloading v0.3.10.tar.gz...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   134    0   134    0     0    310      0 --:--:-- --:--:-- --:--:--   310
>   0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (22) The requested URL returned error: 404
> ==> ERROR: Failure while downloading https://github.com/orinocoz/dripcap/archive/download/v0.3.10.tar.gz
>     Aborting...
> ==> ERROR: Could not download sources.
> Failed to build the package.
> ```

I see the issue. Made a silly mistake when testing locally. Will fix ASAP.

**Comment by noptrix** [comment]
what's going on with this guys?

**Comment by Edu4rdSHL** [comment]
I will fix this today.

**Pull request closed without merging**
