### PR TITLE
beroot: add package

### PR DESCRIPTION
**Pull request by D3vil0p3r**
Waiting for https://github.com/AlessandroZ/BeRoot/pull/40

### CODE REVIEW

**Comment by D3vil0p3r** [comment]
BeRoot is affected by an issue on `sudo_list` module if the system language is different from ENG. Opened https://github.com/AlessandroZ/BeRoot/issues/41

**Comment by D3vil0p3r** [comment]
Waiting for merging https://github.com/AlessandroZ/BeRoot/pull/42

**Comment by D3vil0p3r** [comment]
PR ready to be reviewed and merged. Close https://github.com/BlackArch/blackarch/issues/2478

**Comment by noptrix** [comment]
@D3vil0p3r thanks!

**Pull request merged**
