### PR TITLE
gg_images: initial commit

### LINKED ISSUE #3062: [Tool Request] GG_Images
- **Name**:
GG_Images
- **Source URL**:
https://codeberg.org/nanoory/GG_Images
- **Description**:
Good for OSINT for downloading photos from gg.pl

### PR DESCRIPTION
**Pull request by D4imyo**
This PR fixes #3062

### CODE REVIEW

**Comment by ikstream** [comment]
There was already a PR for this tool #3165. I am not sure why the author closed it, so I would rather wait for a while, if it was by accident.

**Comment by D4imyo** [comment]
> There was already a PR for this tool #3165. I am not sure why the author closed it, so I would rather wait for a while, if it was by accident.

yea i saw it but i don't know either why he closed it so i created the PKGBUILD just in case

**Comment by D4imyo** [comment]
#3165 is open now,
you can close this PR.

**Comment by ikstream** [comment]
Thank you nevertheless @D4imyo.

**Pull request closed without merging**
