### PR TITLE
crackql fixes #3489

### PR DESCRIPTION
**Pull request by dualfade**
please review. pyproject.toml added by the gents.

### CODE REVIEW

**Review by noraj — COMMENTED** [review]
LGTM but why don't you pushed to #3489 directly?

**Comment by dualfade** [comment]
> LGTM but why don't you pushed to #3489 directly?

Rebuilt machine finally. Sorry about that.

**Comment by dualfade** [comment]
Let me know if we can wrap this up. 

Thanks

**Comment by noraj** [comment]
I'll let @noptrix merge this one

**Pull request merged**
